### ISSUE TITLE
[FR] Add support for criteria-level query customization

### ISSUE THREAD

**Issue by keithmccammon** [redcanaryco/surveyor#12]
When running Surveyor, it may be desirable to customize the query at runtime to make results more accurate. 

As an example, when searching for instances of the net.exe command, one may want to exclude processes where the command line includes the parameter "TPAutoConnSvc". In Cb Response queries, this would require appending "-cmdline:TPAutoConnSvc" to the net.exe query at runtime.

**Comment by keithmccammon** [comment]
This is being tracked via branch https://github.com/redcanaryco/cb-response-surveyor/tree/criteria-query-base.

See the notes associated with commit dbcf3dde4901ac22be62e95da7f49e8560c4ddbb for guidance re: using this via a newly formatted definition file.

**Comment by rc-csmith** [comment]
Related to #86
