### ISSUE TITLE
[BUG] AT.exe in 2 defintion files

### ISSUE THREAD

**Issue by rc-abodkins** [redcanaryco/surveyor#32]
**Describe the bug**
AT.exe is located in both Admin Utils and System Utils definition files. Shouldn't it only be included in one for clarity?

**What side of Surveyor is impacted?**
- [x] Definition File

**To Reproduce**
--deffile system-utils.json
--deffile admin-utils.json

**Comment by pmichaudrc** [comment]
Since AT.exe is deprecated and will not execute on newer versions of Windows, it may make sense to create a legacy deffile and migrate it along with other deprecated or older binaries.

**Comment by rc-csmith** [comment]
Removed from system-utils.json in PR #66
