### ISSUE TITLE
New Product: ATP Support

### ISSUE THREAD

**Issue by rc-abodkins** [redcanaryco/surveyor#38]
**Which category is the feature part of?**
- [x] New product support
 
**Use Cases**

**Proposal**
Determine if it is possible to add support for ATP.  

**Additional context**

**Comment by pmichaudrc** [comment]
We may be able to use the Graph API and do advanced hunting queries to pull in Process Execution summaries.

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/run-advanced-query-api

**Comment by jholtmann** [comment]
This was implemented with #44
