### ISSUE TITLE
Make Separate Definition Folders/Files for Window/Mac/Linux

### ISSUE THREAD

**Issue by rc-abodkins** [redcanaryco/surveyor#50]
**Which category is the feature part of?**
- [ ] Carbon Black Response
- [ ] Threat Hunter
- [ ] Definition File
- [x] Code Feature - impacts all products 
- [ ] New product support
 
Make Separate Definition Folders/Files for Window/Mac/Linux

**Comment by gregzee** [comment]
Was this ever added...
