### ISSUE TITLE
Update: active-directory definition file

### ISSUE THREAD

**Issue by pmichaudrc** [redcanaryco/surveyor#56]
**Which category is the feature part of?**
- [ ] Carbon Black Response
- [ ] Threat Hunter
- [x] Definition File
- [ ] Code Feature - impacts all products 
- [ ] New product support
 
**Use Cases**

**Proposal**
Update the contents of the [active-directory](https://github.com/redcanaryco/surveyor/blob/master/definitions/active-directory.json) definition file

**Additional context**

**Comment by rcZachDiehl** [comment]
Myself and @alafrenz42 will take this one.
