### ISSUE TITLE
[FR] Implement Threading Queries

### ISSUE THREAD

**Issue by rc-csmith** [redcanaryco/surveyor#96]
**Which category is the feature part of?**
- [ ] Definition File
- [X] Code Feature 
- [ ] Other (please explain)

**Which product is the feature part of?**
- [X] All products
- [ ] Carbon Black Response
- [ ] Threat Hunter
- [ ] Defender for Endpoint
- [ ] Sentinel1
 
**Use Cases**
For large definition files, having the ability to run threads concurrently prevents the script from getting hung up on a single noisy entry.

**Proposal**
Enable threading to allow multiple queries to be run concurrently. 

**Additional context**
N/A

**Comment by TreWilkinsRC** [comment]
Potential to cause rate limit issues, not prioritized and will not be actioned at this time
